# Basic
title: StonesLuo
subtitle: Laziness is the Sin
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: CV方向硕士研究生在读
# creator: <a href="http://onev.cat">@onevcat</a>

url: "https://stonesluo.github.io/#blog"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color:red

# The blog button should not be removed.
blog_button:
    title: Blogs
    description: Visit blog

# Navigation buttons in the front page.
# nav:
#     - {title: Projects, description: My Projects, url: 'https://github.com/StonesLuo'}
#     # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# # Comment 
# comment:
#     disqus: stonesluo
#     # duoshuo: 
    
# Social
social:
    weibo: 2240449160
    github: StonesLuo
    twitter: 302555998
    # facebook: lei.luo.547
    # gplus: 107108267983477358170
    mail: 302555998@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
